CREATE DATABASE BMS_DB1

USE BMS_DB1

--CUSTOMER PERSONAL INFO

create table CUSTOMER_PERSONAL_INFO
(
	CUSTOMER_ID NVARCHAR(20),
	CUSTOMER_NAME NVARCHAR(30),
	DATE_OF_BIRTH DATE,
	GUARDIAN_NAME NVARCHAR(30),
	ADDRESS NVARCHAR(50),
	CONTACT_NO BIGINT,
	MAIL_ID NVARCHAR(30),
	GENDER CHAR(1),
	MARITAL_STATUS NVARCHAR(10),
	IDENTIFICATION_DOC_TYPE NVARCHAR(30),
	ID_NOC_NO NVARCHAR(10),
	CITIZENSHIP NVARCHAR(20),
	CONSTRAINT CUST_PERS_INFO_PK PRIMARY KEY(CUSTOMER_ID)
);

---CUSTOMER_REFERENCE_INFO


CREATE TABLE CUSTOMER_REFERENCE_INFO
(
	CUSTOMER_ID NVARCHAR(20),
	REFERENCE_ACC_NAME NVARCHAR(20),
	REFERENCE_ACC_NO BIGINT,
	REFERENCE_ACC_ADDRESS NVARCHAR(50),
	RELATION NVARCHAR(25),
	CONSTRAINT CUST_REF_INFO_PK PRIMARY KEY (CUSTOMER_ID),
	CONSTRAINT CUST_REF_INFO_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO
);


--BANK_INFO

CREATE TABLE BANK_INFO(
	IFSC_CODE NVARCHAR(15),
	BANK_NAME NVARCHAR(25),
	BRANCH_NAME NVARCHAR(25),
	CONSTRAINT BANK_INFO_PK PRIMARY KEY(IFSC_CODE)
);

---ACCOUNT INFO

CREATE TABLE ACCOUNT_INFO(
	ACCOUNT_NO BIGINT,
	CUSTOMER_ID NVARCHAR(20),
	ACCOUNT_TYPE NVARCHAR(10),
	REGISTRATION_DATE DATE,
	ACTIVATION_DATE DATE,
	IFSC_CODE NVARCHAR(15),
	INTEREST DECIMAL(7,2),
	INITIAL_DEPOSIT BIGINT,
	CONSTRAINT ACC_INFO_PK PRIMARY KEY(ACCOUNT_NO),
	CONSTRAINT ACC_INFO_PERS_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMER_PERSONAL_INFO,
	CONSTRAINT ACC_INFO_BANK_FK FOREIGN KEY(IFSC_CODE) REFERENCES BANK_INFO
);


INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('HDVL0012','HDFC','KOLKATA');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('SBITNO123','SBI','PATIA');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('ICITNO032','ICICI','PURNIA');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('ICIPG0242','ICICI','MUMBAI');
INSERT INTO BANK_INFO(IFSC_CODE,BANK_NAME,BRANCH_NAME) VALUES('SBISD0113','PNB','SAIDAPET');

SELECT * FROM BANK_INFO

---CUSTOMER_PERSONAL_INFO
INSERT INTO CUSTOMER_PERSONAL_INFO VALUES('C-0021','JHON','1984-06-21','PETER','MUMBAI',889837726,'JOHN@GMAIL.COM','M','MARRIED','JPEG','PM66372','INDIAN')
INSERT INTO CUSTOMER_PERSONAL_INFO VALUES('C-0024','PIYA','1999-10-02','MARIA','JAIDEV BIHAR',994255188,'TERW@GMAIL.COM','F','UNMARRIED','JPEG','PM66372','INDIAN')
INSERT INTO CUSTOMER_PERSONAL_INFO VALUES('C-0022','SONI','2000-11-09','SONAM','CUTTACK',9910355472,'ABC@GMAIL.COM','F','MARRIED','JPEG','PM66372','INDIAN')
INSERT INTO CUSTOMER_PERSONAL_INFO VALUES('C-0028','ALIA','1985-02-17','PUJA','MEDINIPUR',7799018736,'PQR@GMAIL.COM','M','UNMARRIED','JPEG','PM66372','INDIAN')

SELECT  *FROM CUSTOMER_PERSONAL_INFO

